apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.frontend.minReplicas }}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.imageName }}:{{ .Values.frontend.imageVersion }}
          env:
            - name: API_URL
              value: "http://backend"
          ports:
            - name: http
              containerPort: 8080
