apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{ .Values.backend.minReplicas }}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.imageName }}:{{ .Values.backend.imageVersion }}
          ports:
            - name: http
              containerPort: 8888
