apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: http
{{- if eq .Values.frontend.service.type "NodePort" }}
    nodePort: 30000
  type: NodePort
{{- end }}
{{- if eq .Values.frontend.service.type "LoadBalancer" }}
  type: LoadBalancer
{{- end }}
